
language: cpp

matrix:
  include:
      - os: linux
        sudo: false
        compiler: gcc
        env: GCC_VER="7" CMAKE_OPTS="-DCMAKE_BUILD_TYPE:STRING=Debug"
        addons:
          apt:
            sources:
                ubuntu-toolchain-r-test
            packages:
                g++-7
      - os: linux
        sudo: false
        compiler: clang
        env: CLANG_VER="6.0" CMAKE_OPTS="-DCMAKE_BUILD_TYPE:STRING=Debug"
        addons:
          apt:
            sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-trusty-6.0
            - sourceline: 'deb http://apt.llvm.org/trusty/ llvm-toolchain-trusty-6.0 main'
            key_url: 'https://apt.llvm.org/llvm-snapshot.gpg.key'
            packages:
            - clang-6.0
            - libstdc++6
            - g++-7
            env:
            - LINKER_FLAGS="-stdlib=libc++"

before_install:
  - if [ "${GCC_VER}" != "" ]; then export CXX="g++-$GCC_VER" CC="gcc-$GCC_VER"; fi
  - if [ "${CLANG_VER}" != "" ]; then export CXX="clang++-$CLANG_VER" CC="clang-$CLANG_VER"; fi

install:
  pip install --user conan cmake

script:
  - which cmake
  - cmake --version
  - echo $CXX
  - echo $CMAKE_OPTS
  - $CXX --version
  - mkdir build
  - cd build
  - cmake $CMAKE_OPTS  -D CMAKE_EXE_LINKER_FLAGS=${LINKER_FLAGS} ..
  - VERBOSE=1 cmake --build . -- -j2
  - ctest

